### ISSUE TITLE
Dynamic Scaling Stress Relief

### ISSUE THREAD

**Issue by akvanhar** [honeycombio/refinery#1040]
**Refinery is stressed**
Currently, Stress relief is good for scaling up refineries. This issue is tracking the implementation of scaling down refineries in response to stress relief.

**Redis is stressed**
- memory usage is high
  - How to measure it
    - memory stats
    - cache impact per trace
      - how many decisions are made due to timeout v.s. root span arrives
      - time spent in cache * span count
  - Relief strategies
    - log a warning message
    - process faster
      - each individual refinery does deterministic sampling (this is what we do currently)
      - reduce send delay timeout
      - pub/sub refinery stress level and allow refinery to do deterministic sampling for X% of traces based on the overall cluster stress level.

- amount of redis operation is high
  - How to measure it
    - request latency
    - connection pool stats
  - Relief strategies
    - ??

**Comment by VinozzZ** [comment]
We also need to make sure that stress relief can still work without redis

**Comment by VinozzZ** [comment]
This is implemented in 3.x-work-branch
