### ISSUE TITLE
Refinery returns GRPC errors, but doesn't log them

### ISSUE THREAD

**Issue by kentquirk** [honeycombio/refinery#1054]
**Is your feature request related to a problem? Please describe.**

Customer was sending batches of data larger than Refinery was configured to accept. While it did return errors to the sender, it didn't log anything. This is because Refinery uses Husky to accept OTLP traffic, and Husky doesn't have a model for callbacks or telemetry today.

**Describe the solution you'd like**

* 

- [x] Enable Husky to have an error callback or some other mechanism for returning a log message
- [ ] * Hook it into Refinery so that Refinery can log it (and maybe add a metric for GRPC incoming errors as well)

**Describe alternatives you've considered**

The _status quo_

**Additional context**

Inspired by a support ticket.

**Comment by MikeGoldsmith** [comment]
This is the PR where tracing support was added:
- https://github.com/honeycombio/husky/pull/253
