### ISSUE TITLE
Feature Request: Allow trace root context in Dynamic Sampler FieldLIsts

### ISSUE THREAD

**Issue by tdarwin** [honeycombio/refinery#1130]
**Is your feature request related to a problem? Please describe.**
Not a problem, just an enhancement of the current use of root context that can be added to Rule conditions.

**Describe the solution you'd like**
Currently, in rule conditions, you can prefix a field with `root.` to indicate that you only want the condition met if the attribute value is on the root span of a trace.

It would be really nice to add this to the capability of the FieldList in the dynamic sampler configurations, so that you can use a trace's root span data only, to reduce cardinality in the dynamic sampler keyspace.

**Describe alternatives you've considered**
Currently, users do this in instrumentation or with the collector with the transform processor.  But it would support automatic instrumentation better and be less work for customers to just be able to specify the desire to only use the root span in dynamic sampler field lists.

**Additional context**

**Comment by cartermp** [comment]
Another request here: https://honeycomb.productboard.com/all-notes/notes/40970788

**Comment by kentquirk** [comment]
Further request for this in team internal slack. There seems to be some momentum behind this idea. Let's try to make it happen soon.

**Comment by cartermp** [comment]
Also another here: https://honeycomb.productboard.com/all-notes/notes/41039789

It's an avalanche of feedback!
