### ISSUE TITLE
Panic! presumably in /route/route.go "fatal error: concurrent map read and map write"

### ISSUE THREAD

**Issue by senojj** [honeycombio/refinery#1144]
**Versions**

- Go: 1.22.3
- Refinery: 2.5.0

**Steps to reproduce**

1. This is caused by a race condition, but is most likely to occur when the application is starting under heavy load.
2. Observe the application crash when a fatal error occurs due to a concurrent map read and write.

**Additional context**

I would provide the trace of the panic, however, it was stored as multiple individual logs lines within CloudWatch, and there were many active routines. I just wanted to log this so that it has some visibility.

**Comment by TylerHelmuth** [comment]
This issue has been merged to both main (for Refinery 3) and release in Refinery 2.5.1
