### ISSUE TITLE
Bucket sizes for Prometheus histograms

### ISSUE THREAD

**Issue by dcarley** [honeycombio/refinery#115]
The [default bucket sizes](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus?tab=doc#pkg-variables) for [Prometheus histograms](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus?tab=doc#HistogramOpts) are too small to usefully represent metrics like `trace_duration_ms` or `trace_span_count`. I imagine that one size will never suit all and that all of the histograms need to be reviewed independently for appropriate values.

**Comment by martin308** [comment]
@dcarley thanks for bringing this up! I've added it to our backlog for our current period of work on samproxy so that we can prioritize accordingly
