### ISSUE TITLE
Write a Termination message on shutdown

### ISSUE THREAD

**Issue by TylerHelmuth** [honeycombio/refinery#1155]
**Is your feature request related to a problem? Please describe.**
K8s supports a termination message feature that allows you to write out why a container terminated, and uses that message for the LastState details.  Refinery could use this feature to communicate more to its users why/how cleanly it shut down.

**Describe the solution you'd like**
Write out a termination message.  See https://kubernetes.io/docs/tasks/debug/debug-application/determine-reason-pod-failure/

**Comment by kentquirk** [comment]
After reading the link you specified, it looks to me like we'd have to add a configuration parameter to Refinery to specify the location of the termination file (that page assumes it's just stdout, which doesn't really work for refinery). 

Also, we basically only terminate when we receive the termination signal (or crash but I don't think that's a controlled shutdown); what are you expecting to see?

**Comment by kentquirk** [comment]
Quote from Tyler:
I think we can close as not planned

It would require too much k8s-specific stuff in refinery I think

You have to write out the message in a specific place, which would be weird in non-k8s builds
