### ISSUE TITLE
emadynsampler weight Discrepancy 

### ISSUE THREAD

**Issue by mjingle** [honeycombio/refinery#1211]
**Versions**

- Go: N/A
- Refinery: N/A

**Steps to reproduce**

1.

**Additional context**
Forwarding a report from the Docs Site feedback form:

> Weight for the emadynsampler does not show its default value - Looking through the refinery code, this doesn't appear to be set there, instead it looks like it's set in dynsampler-go instead: https://github.com/honeycombio/dynsampler-go/blob/fd56ea90d9315f7204a9a20c1065587983d456ee/emasamplerate.go#L43-L48
> Can you please document this?
> Docs Page URL: https://docs.honeycomb.io/manage-data-volume/sample/honeycomb-refinery/sampling-methods/#ema-dynamic-sampler

This may be a documentation issue, or a Refinery bug. Happy to help either way.

**Comment by kentquirk** [comment]
Turns out we're not doing defaults for most of this stuff, so I'll be fixing that.
