### ISSUE TITLE
Ability to drop stress recalculation logs

### ISSUE THREAD

**Issue by cartermp** [honeycombio/refinery#1222]
From a customer:

"We're storing them only in our test environment so we can debug issues while we onboard our services onto honeycomb+refinery. It saves us from having to re-deploy refinery every time we want to onboard a new service"

They would like functionality to remove the stress recalc logs as these are causing the most bloat in their instance and making them run above their limits.

**Comment by kentquirk** [comment]
This is already debug-level logging; most likely the best strategy is to only use info except for a few hours when actively debugging a problem.
