### ISSUE TITLE
Redis peer configuration option to use FQDN instead of Hostname?

### ISSUE THREAD

**Issue by lewisf** [honeycombio/refinery#124]
In GKE, pods can be resolved using their FQDN (if a headless service is set up) but unless I'm missing something I think the self-reported hostnames don't resolve?

I've forked the project to use FQDN in my own deployment and everything works perfectly. Is it was worth introducing this as a configurable option?

**Comment by cartermp** [comment]
Will close this in favor of https://github.com/honeycombio/refinery/issues/858, as this is a different mechanism, but allows Refinery to work in GCP.
