### ISSUE TITLE
Support Redis cluster mode

### ISSUE THREAD

**Issue by kentquirk** [honeycombio/refinery#1286]
**Is your feature request related to a problem? Please describe.**

AWS defaults to cluster mode, so we just need to enable people to use it.

**Describe the solution you'd like**

Config option for it. Our redis library supports it with the Universal Client we use, so we need to enable it. It's slightly tricky to get the config right, but we'll figure it out.

**Comment by VinozzZ** [comment]
we can ask @tdarwin to see if they would be willing to help us to set up a elasticcache instance with cluster mode enabled

**Comment by VinozzZ** [comment]
aggregating drop messages to reduce the volume of pubsub messages in the cluster
