### ISSUE TITLE
Forward only key fields to peers

### ISSUE THREAD

**Issue by VinozzZ** [honeycombio/refinery#1318]
We will extend the existing peer span forwarding system to include forwarding a “proxy span” to its decider node. This proxy span will include:

- Key fields necessary for trace decisions (this can be empty if no key fields are present).
- A marker that differentiates proxy spans from normal spans.

Conditions for Forwarding a Proxy Span:
- ForceTraceLocality is set to false.
- A new span arrives, even if it does not contain any key fields.

Ignoring Proxy Spans:
When sending spans to Honeycomb, Refinery should ignore proxy spans by checking the marker to ensure they are not forwarded.

**Comment by MikeGoldsmith** [comment]
Requires the following issue to be resolved first:
- #1325
