### ISSUE TITLE
Collector loop taking longer than expected

### ISSUE THREAD

**Issue by TylerHelmuth** [honeycombio/refinery#1375]
**Versions**

- Refinery: 2.8.x

**Steps to reproduce**

1. Send a lot of data through refinery
2. Observe that sometimes the msg `IsAlive: subsystem dead due to timeout` is recorded for the `collector` subsystem.

**Additional context**

Ever since we added the collect loop to the health check system in 2.8.0 we now see it sometimes take longer than 3 seconds to complete its work. We added support for configuring this timeout value in 2.8.3, but it would be good to investigate why it is taking a long time and if there are any performance improvements that can be made.

**Comment by VinozzZ** [comment]
One proposed idea is to start a goroutine to asynchronously send all spans in a trace, preventing the collect loop from being blocked.

**Comment by TylerHelmuth** [comment]
Through a lot of tracing of the collect loop we found `GetSampleRate`, specifically for a Rules-Based sampler using the EMA dynamic sampler, to be the culprit.  There is a lock in that sampler to allow it do make the calculations it needs.  If we are trying to make a sampling decision during the lock we end up having to wait.  Process enough traces in a single time through collect and this adds up.

Changing the sampler would be quite difficult.  Instead we'll opt to process less traces each time through the collect loop.
