### ISSUE TITLE
spans_sent metric

### ISSUE THREAD

**Issue by ebracho** [honeycombio/refinery#1422]
Would it be possible to emit a `spans_sent` metric? This would give us a way to create triggers based on ingested span volumes. 

**Is your feature request related to a problem? Please describe.**

Need a way to create a trigger based on ingested span volumes. 

**Describe the solution you'd like**

Emit a `spans_sent` counter metric that increments for each spend sent to Honeycomb's ingestion endpoint. 

**Describe alternatives you've considered**

Create a trigger based on a simple COUNT query
* Usage queries aren't supported for triggers, no way to disable sample rate adjustments for triggers. 

**Additional context**

**Comment by kentquirk** [comment]
We like this idea and will try to get it in the next release.

**Comment by MikeGoldsmith** [comment]
Closing as we already have the `libhoney_upstream_messages_sent` counter that tracks the number of events sent to Honeycomb. It's part of the standard Refinery Metrics.

**Comment by ebracho** [comment]
Oh perfect, thanks for pointing it out. I noticed that metric before but I didn't realize it was referring to span counts.
