### ISSUE TITLE
Support for Redis with Authentication/Password

### ISSUE THREAD

**Issue by blackbaud-brandonstirnaman** [honeycombio/refinery#184]
My org only deploys PaaS-y instances of Redis, specifically Azure Cache for Redis and I'd like to be able to use an instance from that service to support Refinery.

This would require the ability to specify a password and to require TLS/SSL. I'll poke around to see if I can assist but it felt useful to open an issue first.

**Comment by eanakashima** [comment]
@blackbaud-brandonstirnaman thanks for the Issue. This unfortunately isn't on our immediate roadmap, but we would be happy to look at a PR if you feel up to tackling this yourself — definitely feel free to ask us in [Pollinators #discuss-refinery-beta](https://join.slack.com/share/zt-i8lsxj1h-rAYHXj9z0LETfFDZwfONsw) if you have questions about implementation.

**Comment by Vlaaaaaaad** [comment]
This is similar to https://github.com/honeycombio/refinery/issues/103 🙂  I focused on TLS in that issue, but mentioned passwords too.

**Comment by blackbaud-brandonstirnaman** [comment]
A member of my team contributed this functionality. Closing!
