### ISSUE TITLE
Sample config is missing some quotes

### ISSUE THREAD

**Issue by kevincantu** [honeycombio/refinery#194]
Inside the sample [rules.toml](https://github.com/honeycombio/refinery/blob/442e269/rules.toml#L10) there are sample values (commented out) for setting these:
```
DryRun = true
...
DryRunFieldName = refinery_kept
```

If you uncomment them the second needs quotes:
```
% docker run --rm -it --volume $(pwd):/etc/refinery --expose 8080 --publish 44444:8080 honeycombio/refinery:latest /usr/bin/refinery
unable to load config: While parsing config: (10, 19): no value can start with r
```

**Comment by MikeGoldsmith** [comment]
Thanks for raising the bug @kevincantu  - we'll take a look and get it fixed up.

**Comment by MikeGoldsmith** [comment]
All done now @kevincantu - thanks again.

**Comment by kevincantu** [comment]
🐬
