### ISSUE TITLE
Clarification around expected timeouts/backpressure when honeycomb API slows down?

### ISSUE THREAD

**Issue by BRMatt** [honeycombio/refinery#245]
[The other day in the pollinators slack](https://honeycombpollinators.slack.com/archives/C01BZ3J7RMJ/p1617288681019400) several folks noticed that their refinery clusters all had buffer overruns at the same time. After a bit of discussion it came to light that the honeycomb API had been having a bit of a slowdown around that time, which caused requests to the honeycomb API to stall and put backpressure on refinery's cache.

It seems like the metrics that honeycomb emits don't include statistics about how long upstream API requests are taking - would it be possible to add support for these metrics so that operators can understand if performance/capacity issues are related to the honeycomb API?

On a related note, it appears that libhoney configures a 60s timeout on all upstream requests. Given the decision to change the timeout from 10 seconds to 60 seconds [was made 2 years ago](https://github.com/honeycombio/libhoney-go/pull/40/files#diff-b54b80be29385d2c71d21d0461d53b8070b5b0ef546675deca24d0ec088b71b8R74-R75) I was wondering if that's still an appropriate timeout, or if a lower value would be more suitable?

For reference, here're some charts of what our refinery cluster looked like during the incident. You can see how our refinery instance started dropping incoming spans almost as soon as the API slowdown occurred (the upstream_response_errors_peer is actually for the honeycomb API, not refinery peers - see #244). The point where memory usage drops is where the instance OOMs and restarts:

![image](https://user-images.githubusercontent.com/20394/114064444-9278c400-9891-11eb-9157-f69a9812b92b.png)

As an aside, it's not really clear to me why the collect_cache_entries_max metric just disappears as soon as the system starts experiencing backpressure - is that something you would expect to happen?

**Comment by cartermp** [comment]
We'll likely close this out. So much has changed with Refinery, including improving its resiliency. Additionally, we have been exploring what to do when honeycomb is down or experiencing significantly degraded services.
