### ISSUE TITLE
InsecureSkipVerify does not work. Request to make it a config

### ISSUE THREAD

**Issue by verajohne** [honeycombio/refinery#251]
Right now there is no option to use InsecureSkipVerify. It would be nice if this could be a config option, like `UseTLS`.

The addition of SkipVerify in the options [here](https://github.com/honeycombio/refinery/blob/3255ce65cb83539428d12f7e6dd26d3527b0e1ac/internal/peer/redis.go#L186) is a noop as `InsecureSkipVeridy` is only set if tlsConfig is nil [here](https://github.com/gomodule/redigo/blob/72af8129e040d6f962772a8c582e5e9f22085788/redis/conn.go#L246).

I proposed a solution in https://github.com/honeycombio/refinery/pull/249, in this commit https://github.com/honeycombio/refinery/pull/249/commits/e1620f06c26ae756b0cb459a4b002a40f9b6451c. @vreynolds requested our use case for InsecureSkipVerify. Heroku Redis uses self signed certs so in order to run refinery in a Heroku private/shield space along with our application we need to set InsecureSkipVerify=true. This will also apply to Heroku's customers.

**Comment by vreynolds** [comment]
Thanks for the extra details @verajohne! That sounds legit. How about a config option to `useTLSInsecure`?

**Comment by verajohne** [comment]
> Thanks for the extra details @verajohne! That sounds legit. How about a config option to `useTLSInsecure`?

That would be great :)

**Comment by beanieboi** [comment]
@vreynolds I think this can be closed since #254 got merged.
