### ISSUE TITLE
Add arbitrary static attribute name/values to refinery telemetry

### ISSUE THREAD

**Issue by bdarfler** [honeycombio/refinery#260]
When running more than 1 refinery cluster there is no way to differentiate the telemetry from each cluster.  

Allow the refinery operator to configure attribute name/values that will be added to all metrics and logs emitted by Refinery.

**Comment by seh** [comment]
See [this thread in the "discuss-refinery" channel](https://honeycombpollinators.slack.com/archives/C01BZ3J7RMJ/p1641493326005300)  of the "Honeycomb Pollinators" Slack workspace for a similar request.

**Comment by fchikwekwe** [comment]
Fixed by #621
