### ISSUE TITLE
Make grpc ServerParameters configurable

### ISSUE THREAD

**Issue by bdarfler** [honeycombio/refinery#263]
gRPC has a set of [ServerParameters](https://pkg.go.dev/google.golang.org/grpc/keepalive#ServerParameters) that we should make configurable.

Specifically, the MaxConnectionAge and MaxConnectionAgeGrace are of interest to help keep gRPC connections balanced across a pool of refinery hosts.

An issue can arise when a host dies that all the connections will failover to the other hosts and remain there due to the long-lived nature of gRPC connections. The new host that spins up to replace the dead host will never receive any incoming connections and is then underutilized while the other hosts are overburdened.

**Comment by kentquirk** [comment]
This continues to be a problem, and it won't be a big lift; some teams want to use gRPC and not otlp-over-http.

**Comment by abatilo** [comment]
I've opened a PR to attempt to implement these changes! Please take a look whenever convenient:
https://github.com/honeycombio/refinery/pull/499

Thanks!
