### ISSUE TITLE
Feature: Support "does-not-contain" as operator

### ISSUE THREAD

**Issue by tr-fteixeira** [honeycombio/refinery#265]
Hello, 

Seems like not all ui/api operators from the platform are supported on the RuleBasedSampler, [here](https://github.com/honeycombio/refinery/blob/main/sample/rules.go#L56). 

When using one of the unsupported operators, there is no indication of error, it just doesn't match the desired trace/span. 
It is also not documented anywhere (that i could find). 

Im looking specifically for that one, but would be nice to have them all =)

Regards,

**Comment by MikeGoldsmith** [comment]
Closing this issue now #267 was merged. #266 will be use to track enhanced rules validation.
