### ISSUE TITLE
Enhancement: Validate operators supported on RulesBasedSampler when parsing the rules

### ISSUE THREAD

**Issue by tr-fteixeira** [honeycombio/refinery#266]
This is related to https://github.com/honeycombio/refinery/issues/265 . 

It would have been a LOT easier to understand why the rules were not being applied/evaluated properly if we had the indication that those are not supported. 

This does not need to fail the parse, or could, this depends on the team preference for those failure modes.  Let me know what you guys would prefer 👍 

Regards,

**Comment by irvingpop** [comment]
We're noticing a lot of customers are getting burned by Refinery silently ignoring rules that are malformed in any way.  It's rather difficult to troubleshoot.

**Comment by irvingpop** [comment]
Couple of recent examples, from customers who used the bad dot.notation examples from the helm repo. Namely these two: 
* https://github.com/honeycombio/helm-charts/pull/169/files 
* https://github.com/honeycombio/helm-charts/pull/163/files
