### ISSUE TITLE
Refinery Metrics are three different event goroutines instead of a single, aggregated event

### ISSUE THREAD

**Issue by jharley** [honeycombio/refinery#294]
Refinery Metric Events are running in three separate go routines (`metrics`, `upstreamMetrics`, and `peerMetrics`) which can lead to instances where a single millisecond has three different metrics events published (each containing their own data along with the dynamic fields).

Ideally, these three different events would get pre-aggregated into a single coherent event.

Originally opened as #293, which was closed after further investigation.

**Comment by kentquirk** [comment]
#593 unified all the metrics into a single object. I'm hoping this will address this problem appropriately, although it wasn't a consideration in the redesign.
