### ISSUE TITLE
How to make TotalThroughputSampler in terms of events per second

### ISSUE THREAD

**Issue by william-tran** [honeycombio/refinery#296]
We have traces that vary in in length substantially, and want to use TotalThroughputSampler to help us stay within rate limits, but having it sample in terms of traces per second results in too much variability in the output events per second.

Calls to the underlying dynsampler are done one per trace, which to my understanding increments the internal counter once per trace:

https://github.com/honeycombio/refinery/blob/v1.4.0/sample/totalthroughput.go#L58

To make this in terms of events per second, I see the only way to do this would be to call that line above in a loop, where the iterations == the number of spans in the trace, but that would be a pretty inefficient way of making this work. What approach would you recommend?

**Comment by MikeGoldsmith** [comment]
Hey @william-tran - thanks for creating the issue.

We agree incrementing the counter in a loop for each span within a given trace would be inefficient and wouldn't be compatible with current usage of the TotalThroughputSampler.

We'd need sometime to think about this, we'll put it on our backlog for prioritisation and may get back in touch to ask more questions. Thank you.

**Comment by cartermp** [comment]
This was done in Refinery 2.0!
