### ISSUE TITLE
Capture and handle missing gRPCListenAddr for OTLP/gRPC requests

### ISSUE THREAD

**Issue by MikeGoldsmith** [honeycombio/refinery#313]
If a refinery config does not include a GRPCListenAddr and OTLP/gRPC requests are sent, requests use a fallthrough proxy path and produce unuseable data. Logs do not clearly indicate what has happened.

Refinery should reject gRPC requests if the gRPCListAddr is missing and clearly log why requests are rejected.

**Comment by JamieDanielson** [comment]
We have been unable to reproduce the scenario of gRPC requests not being properly rejected when a GRPCListenAddr is missing from the config. If this continues to be an issue please feel free to reopen.
