### ISSUE TITLE
MinCacheCapacity to prevent Refinery from iteratively reducing its cache capacity

### ISSUE THREAD

**Issue by leonsp-ai** [honeycombio/refinery#340]
**Is your feature request related to a problem? Please describe.**
Refinery detects when it's low on memory and changes its cache capacity configuration to 90% of current cache usage. If this does not free up memory, it will do this repeatedly, thus exponentially shrinking its cache capacity.

For example:
![image](https://user-images.githubusercontent.com/60105412/138168408-23deccaf-6d92-4987-bcec-bd7664aacd0c.png)

**Describe the solution you'd like**
- A `MinCacheCapacity` configuration setting to provide a floor to automatic cache capacity reductions.

**Describe alternatives you've considered**
- An option for an automatic graceful exit in case of low memory. Refinery would terminate and Kubernetes would replace that Refinery pod.
- Memory profiling of Refinery to identify any possible memory leaks, reduce allocations, and to make garbage collection more effective.

**Additional context**
- This is following up on a discussion in https://github.com/honeycombio/refinery/issues/339

**Comment by jtthackery** [comment]
This would help us as well, we infrequently (~1x week or less) ingest very large traces, typically 2 or 3 orders of magnitude larger than our median trace size, but we see permanent effects on `CacheCapacity`, forcing us to either restart our cluster or increase our node count.

We're working on reducing/removing the codepaths that lead to those massive traces for reasons unrelated to Refinery, but until that time this is a bit itchy to have to handle.

**Comment by kentquirk** [comment]
We chose to solve this another way, with #547, which introduces a new cache management strategy that doesn't resize the cache, but instead ejects "large" traces early if necessary.
