### ISSUE TITLE
Use gauges not histograms

### ISSUE THREAD

**Issue by bdarfler** [honeycombio/refinery#346]
**Is your feature request related to a problem? Please describe.**

Prometheus Histograms are confusing. User's don't understand them. A quick google search turns up articles like "Hisograms with Prometheus: A Tale of Woe" and more importantly, we have confused customers that reach out to us in [Pollenators](https://honeycombpollinators.slack.com/archives/C01BZ3J7RMJ/p1635509296050900) about them as well as customers that open up [issues](https://github.com/honeycombio/refinery/issues/339#issuecomment-942646548) based in part on misinterpretations of them.

Additionally, we have failed to understand them in the past which resulted in #115. Trying to fix our very broken Prometheus histograms is non-trivial because Refinery's internal metrics interface doesn't allow different settings per metric and even if it did it's unclear we could find a good value that works across the variety of traffic and host configurations that our customers run Refinery in.

**Describe the solution you'd like**

Rather than continue to leverage Prometheus histograms which are confusing to our customers and difficult to properly configure we should remove histograms altogether and use gauges instead. 

Currently, the Honeycomb metrics reporter reports every 1s which seems granular enough that switching to a gauge wouldn't impact operability. We would want to recommend that Prometheus users scrape between every 1 and 10 seconds to ensure they get the right level of granularity.

**Comment by bdarfler** [comment]
Some good conversation about this proposal here - https://honeycombpollinators.slack.com/archives/C01BZ3J7RMJ/p1637596828141500

**Comment by kentquirk** [comment]
I've been noodling on this for a while; while I think there are some metrics (like queue lengths) that might be acceptable as gauges, the nice property of histograms is that they capture extreme values. In my ideal world, we'd use different buckets for the different histograms -- but for now, the ones we have are acceptable, and with the impending arrival of exponential histograms to an otel near you (sometime in the next few months, anyway), I would prefer to leave these alone, and convert to exponential histograms someday.
