### ISSUE TITLE
Runtime metrics are not available on prometheus endpoint

### ISSUE THREAD

**Issue by akasprzok** [honeycombio/refinery#351]
The Honeycomb documentation mentions several [runtime metrics](https://docs.honeycomb.io/manage-data-volume/refinery/scale-and-troubleshoot/#understanding-refinerys-metrics) that are not available via the prometheus endpoint.

Possible solutions are to have the docs differentiate between what metrics are available via prometheus vs metrics sent directly to HC, or to add the runtime metrics to the Prometheus endpoint.

For users of the Prometheus metrics, the latter solution - adding the missing metrics - would be preferable.

**Comment by JamieDanielson** [comment]
Thank you for raising this issue @akasprzok.

We'll start with updating the documentation to ensure it's clear that some of the metrics referenced (e.g. `process_uptime_seconds`) are not available when using Prometheus vs. sending directly to Honeycomb.

We'll add to our backlog for closing the gap on metrics not currently available via the Prometheus endpoint.
