### ISSUE TITLE
"HoneycombMetricsConfig.MetricsHoneycombAPI" field should not be required

### ISSUE THREAD

**Issue by seh** [honeycombio/refinery#377]
**Versions**

- Go: 1.17.5
- Refinery: 1.8.1

**Steps to reproduce**

1. Activate publishing metrics to Honeycomb by populating the "HoneycombMetrics" field in the Refinery configuration file.
1. Omit the "HoneycombMetrics.MetricsHoneycombAPI" field.
1. Observe that Refinery exits with an error, complaining:  
  > unable to load config: Key: ‘HoneycombMetricsConfig.MetricsHoneycombAPI’ Error:Field validation for ‘MetricsHoneycombAPI’ failed on the ‘required’ tag

**Additional context**

[The "MetricsHoneycombAPI" field is tagged](https://sourcegraph.com/github.com/honeycombio/refinery@3b9fe364feff08525ea3306070064b61d632ceef/-/blob/config/file_config.go?L75) as needing to parse as a valid URL, and is marked as required. However, [we pass it down to _libhoney_ in the `libhoney.ClientConfig.APIHost` field](https://sourcegraph.com/github.com/honeycombio/refinery@3b9fe364feff08525ea3306070064b61d632ceef/-/blob/metrics/honeycomb.go?L113), and [that field is documented to have a sensible default value](https://github.com/honeycombio/libhoney-go/blob/6bbb37b8cafcce767948992f2c687ae76abeb9ea/client.go#L49-L51) that callers should not need to override in most cases.

It's fine to validate that the "MetricsHoneycombAPI" field is a URL if its value is nonempty, but we should not require this field be populated, just as [we don't require a value for the similar "HoneycombAPI" field](https://sourcegraph.com/github.com/honeycombio/refinery@3b9fe364feff08525ea3306070064b61d632ceef/-/blob/config/file_config.go?L110).

**Comment by seh** [comment]
I recognize that it would be hard to define a default in Viper for these fields, as the `HoneycombLoggerConfig` fields shouldn't be used if _logrus_ is in use. The same goes for `HoneycombMetricsConfig` and Prometheus being in use. Perhaps just relaxing the constraint and allowing the default zero value—the empty string—would be sufficient here, relying on _libhoney-go_ to supply the concrete default value.

That, or consider copying down the value from the top-level `HoneycombAPI` field, though that would be a change in behavior, possibly surprising some existing users.

**Comment by cartermp** [comment]
I think we can close this out considering the changes made to configuration and metrics in Refinery 2.0.
