### ISSUE TITLE
Separate MaxBatchSize config for Peers and Upstream

### ISSUE THREAD

**Issue by jwilm** [honeycombio/refinery#381]
**Is your feature request related to a problem? Please describe.**

We are running a 16 node Refinery cluster with 32 Refinery processes. At smaller cluster sizes, we had issues with the peer queue overflowing and dropping a ton of data. We found that increasing the `MaxBatchSize` from the default of 512 to 4x that value at 2,048 allowed our peer queue to drain quickly enough to rarely overflow (we have a large peer buffer as well).

Unfortunately as we did this, we increased the volume of upstream errors described by this log line:

```
time="2022-01-21T22:42:09Z" level=error msg="error when sending event" api_host= dataset= error="event exceeds max event size of 100000 bytes, API will not accept this event" event_type= status_code=0 target=
```

**Describe the solution you'd like**

An 80/20 solution here is to allow independent configuration of the peer and upstream max batch sizes. This is relatively quick to implement, and I'd be happy to contribute the patch myself, but it's not a sure thing in the face of large spans. There's still the potential for even smaller batches to trigger this error.

**Describe alternatives you've considered**

A more robust solution might be an adaptive batch size with a target payload size. Rather than hitting the 100kB error and discarding the data, splitting the batch and retrying could improve things. Even better would be if the payload size could be known ahead of time such that the error is entirely avoided except for extremely large spans.

**Additional context**

We are currently dropping a ton of data that would otherwise be sent to Honeycomb.

**Comment by MikeGoldsmith** [comment]
Hi @jwilm

Thank you for raising creating the issue. I think your two suggestions to improve control of peer batch sizes are good and see the merit in both approaches. We will discuss internally and report here.

**Comment by jwilm** [comment]
I ran an experiment with the config split out as described above, and it had no effect on the rate of these errors (deployed ~1400 Tuesday): 
![image](https://user-images.githubusercontent.com/4285147/151215006-4d34e984-1c96-444b-b853-b93fd9b6eb84.png)

This isn't surprising in hindsight as this is supposed to be an error about a single event rather than the bulk batch size (which I believe has a 5MB limit per batch). The reason I had been thinking to the contrary initially was due to apparently coincidental timing of these error rates increasing with when we 4x'd our MaxBatchSize config. In reality, that config change allowed our Refinery to actually send more data to Honeycomb, so more rejections of this sort are not a surprise.

That said, this might still be useful configuration, but the urgency is not what we initially thought. Please let me know if you'd like me to open a PR with my work (linked above).

Thanks again!

**Comment by MikeGoldsmith** [comment]
Thanks for reporting your progress.

Closing for now.
