### ISSUE TITLE
Huge data loss when deploying configuration _without_ restarting systemd service

### ISSUE THREAD

**Issue by looneym** [honeycombio/refinery#384]
**Versions**

- Go: `go version go1.11.4 linux/amd64`
- Refinery: `1.7.0-1`

Hey folks 👋 

We're seeing almost total dropping of traces at the refinery level when we attempt to deploy config files _without_ issuing a restart.  

On change to the repository that stores our`refinery.toml` and `rules.toml` files, we push the new code out to all nodes, replace the config files in `/etc/refinery`, and issue a `systemctl restart refinery`. The `restart` was done out of convenience when we began spiking refinery in order to iterate quickly on rules. We understand that `restart` is unnecessary in most cases (since the live reload mechanism will pick up most changes to rules) and can cause unintended sampling behaviour as refinery will forward all traces in it's buffer to Honeycomb on shutdown. We are trying to remove this `restart` call from our deployment lifecycle scripts by changing it to a `systemctl start` call (which should be a noop if a service is already running) but any time we attempt to do so, the amount of traces making it through to Honeycomb falls almost to zero:

For example, deploying this change:

![image](https://user-images.githubusercontent.com/12705417/151217561-23bd003f-76df-4d2f-a4b9-f9ed54e8aee4.png)

Resulted in this behaviour:

![image](https://user-images.githubusercontent.com/12705417/151217346-835a8d69-56d9-45b8-934e-6c7742faf1e9.png)

I've also tried logic to only issue a `start` in the event that the service is not running, which resulted in the same behaviour:

![image](https://user-images.githubusercontent.com/12705417/151218726-7d2b76df-09a0-48c0-9be0-2acce1454e0d.png)

When we do this, we see the following impact on our refinery metrics. The change was merged at ~18:05 and reverted at ~19:40
![image](https://user-images.githubusercontent.com/12705417/151219484-a398103e-a0da-4c87-a50a-b92b0ce4ca81.png)

Our deployment lifecycle runs two scripts, in order: 

<details>
 <summary> 001_install_refinery </summary>

```ruby
#!/usr/bin/env ruby

require 'json'
require 'erb'

MUSTER_APP_NAME = ENV["MUSTER_APP_NAME"]
MUSTER_PROFILE = ENV["MUSTER_PROFILE"]
SLUG_PATH = "/apps/#{MUSTER_APP_NAME}/current"
PROFILE_PATH = File.join(SLUG_PATH, "muster/profiles/#{ENV["MUSTER_CLUSTER_PATH"]}")
REFINERY_VERSION = "1.7.0-1"

def config_vars
  # super secret stuff happens here
end

def install_refinery
  `rpm --quiet -q refinery-#{REFINERY_VERSION}.x86_64 || sudo rpm -i --force "https://s3.amazonaws.com/REDACTED/refinery-#{REFINERY_VERSION}.x86_64.rpm"`
end

def write_config_file
  template = "#{SLUG_PATH}/muster/refinery.toml.erb"

  @refinery_metrics_dataset_key = config_vars["refinery_metrics_dataset_key"]
  @hostname = `ec2-metadata`.match(/local-hostname: ([^\s]+)/)[1]

  renderer = ERB.new(File.read(template))
  File.write("/etc/refinery/refinery.toml", renderer.result)
end

def write_rules_file
  template = "#{SLUG_PATH}/muster/rules.toml.erb"

  renderer = ERB.new(File.read(template))
  File.write("/etc/refinery/rules.toml", renderer.result)
end


install_refinery
write_config_file
write_rules_file

```
</details>

<details>
 <summary> 002_start_refinery  </summary>

```bash
#!/usr/bin/env bash

set -eux

systemctl start refinery.service
```

</details>

The only thing I can think of here is that overwriting the files with `File.write` might be causing the livereload mechanism to misbehave in some way?

**Steps to reproduce**

1.  Have an existing refinery process running on a linux host under systemd
2. Rewrite `refinery.toml` and `rules.toml`, either with new configuration *or* with the exact same configuration as before
3. Do not run `systemctl restart` 
4. Refinery drops traces

**Comment by looneym** [comment]
Deployment logs, showing `systemctl status` before and after the deploy, note the service has not changed status:

```
[ec2-user@honeycomb-refinery-production-proxy ~]$ systemctl status refinery
● refinery.service - Refinery Honeycomb Trace-Aware Sampling Proxy
   Loaded: loaded (/usr/lib/systemd/system/refinery.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2022-01-26 18:10:54 UTC; 5min ago
 Main PID: 946227 (refinery)
   CGroup: /system.slice/refinery.service
           └─946227 /usr/bin/refinery -c /etc/refinery/refinery.toml -r /etc/refinery/rules.toml

Jan 26 18:16:27 honeycomb-refinery-production-proxy.i-00335b28b8d8afe9e refinery[946227]: time="2022-01-26T18:16...
Jan 26 18:16:27 honeycomb-refinery-production-proxy.i-00335b28b8d8afe9e refinery[946227]: time="2022-01-26T18:16...
Jan 26 18:16:27 honeycomb-refinery-production-proxy.i-00335b28b8d8afe9e refinery[946227]: time="2022-01-26T18:16...
Jan 26 18:16:27 honeycomb-refinery-production-proxy.i-00335b28b8d8afe9e refinery[946227]: incr, eIdx: 9, len(evs...
Jan 26 18:16:27 honeycomb-refinery-production-proxy.i-00335b28b8d8afe9e refinery[946227]: incr, eIdx: 10, len(ev...
Jan 26 18:16:27 honeycomb-refinery-production-proxy.i-00335b28b8d8afe9e refinery[946227]: incr, eIdx: 11, len(ev...
Jan 26 18:16:27 honeycomb-refinery-production-proxy.i-00335b28b8d8afe9e refinery[946227]: incr, eIdx: 12, len(ev...
Jan 26 18:16:27 honeycomb-refinery-production-proxy.i-00335b28b8d8afe9e refinery[946227]: incr, eIdx: 13, len(ev...
Jan 26 18:16:27 honeycomb-refinery-production-proxy.i-00335b28b8d8afe9e refinery[946227]: incr, eIdx: 14, len(ev...
Jan 26 18:16:27 honeycomb-refinery-production-proxy.i-00335b28b8d8afe9e refinery[946227]: incr, eIdx: 15, len(ev...
Hint: Some lines were ellipsized, use -l to show in full.
[ec2-user@honeycomb-refinery-production-proxy ~]$ <deployment initiated>
I, [2022-01-26T18:16:35.133056 #950084]  INFO -- : Running 'MUSTER_APP_NAME=honeycomb-refinery MUSTER_PROFILE=honeycomb-refinery-production-proxy MUSTER_CLUSTER_PATH=production-proxy MUSTER_SHA=a9859ec20a49cbc968e6dbf338055918635293cd RAILS_ENV=production /apps/honeycomb-refinery/current/bin/slugexec /apps/honeycomb-refinery/current/muster/lifecycle/superuser-start/001_install_refinery' ...
I, [2022-01-26T18:16:36.134678 #950084]  INFO -- : Running 'MUSTER_APP_NAME=honeycomb-refinery MUSTER_PROFILE=honeycomb-refinery-production-proxy MUSTER_CLUSTER_PATH=production-proxy MUSTER_SHA=a9859ec20a49cbc968e6dbf338055918635293cd RAILS_ENV=production /apps/honeycomb-refinery/current/bin/slugexec /apps/honeycomb-refinery/current/muster/lifecycle/superuser-start/002_start_refinery' ...
+ systemctl start refinery.service
I, [2022-01-26T18:16:37.136316 #950084]  INFO -- : Deploy successful
I, [2022-01-26T18:16:37.136437 #950084]  INFO -- : Fetching instance tags
[ec2-user@honeycomb-refinery-production-proxy ~]$ systemctl status refinery
● refinery.service - Refinery Honeycomb Trace-Aware Sampling Proxy
   Loaded: loaded (/usr/lib/systemd/system/refinery.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2022-01-26 18:10:54 UTC; 5min ago
 Main PID: 946227 (refinery)
   CGroup: /system.slice/refinery.service
           └─946227 /usr/bin/refinery -c /etc/refinery/refinery.toml -r /etc/refinery/rules.toml

Jan 26 18:16:34 honeycomb-refinery-production-proxy.i-00335b28b8d8afe9e refinery[946227]: incr, eIdx: 26, len(ev...
Jan 26 18:16:34 honeycomb-refinery-production-proxy.i-00335b28b8d8afe9e refinery[946227]: incr, eIdx: 27, len(ev...
Jan 26 18:16:34 honeycomb-refinery-production-proxy.i-00335b28b8d8afe9e refinery[946227]: incr, eIdx: 28, len(ev...
Jan 26 18:16:34 honeycomb-refinery-production-proxy.i-00335b28b8d8afe9e refinery[946227]: incr, eIdx: 29, len(ev...
Jan 26 18:16:35 honeycomb-refinery-production-proxy.i-00335b28b8d8afe9e refinery[946227]: time="2022-01-26T18:16...
Jan 26 18:16:35 honeycomb-refinery-production-proxy.i-00335b28b8d8afe9e refinery[946227]: incr, eIdx: 3, len(evs...
Jan 26 18:16:35 honeycomb-refinery-production-proxy.i-00335b28b8d8afe9e refinery[946227]: time="2022-01-26T18:16...
Jan 26 18:16:35 honeycomb-refinery-production-proxy.i-00335b28b8d8afe9e refinery[946227]: incr, eIdx: 4, len(evs...
Jan 26 18:16:35 honeycomb-refinery-production-proxy.i-00335b28b8d8afe9e refinery[946227]: time="2022-01-26T18:16...
Jan 26 18:16:35 honeycomb-refinery-production-proxy.i-00335b28b8d8afe9e refinery[946227]: incr, eIdx: 196, len(e...
```

While the deployment was happening, I was monitoring the output of the systemd service with `sudo journalctl -f -u refinery`. There is no output. The log lines there are from the service running before the deployment was initiated. 

![image](https://user-images.githubusercontent.com/12705417/151223323-5122606b-e5d8-4ae8-84e2-fb99f0f82933.png)

**Comment by jharley** [comment]
I'm curious if this is potentially showing up as https://github.com/honeycombio/helm-charts/issues/101 as well? 🤔

**Comment by looneym** [comment]
Modifying our deployment script to use `cp` instead of `File.write` seems to fix this 😅

![image](https://user-images.githubusercontent.com/12705417/151400532-bdca6996-15ee-42b2-b6d5-af7daf0de500.png)

**Comment by MikeGoldsmith** [comment]
Thanks for the update @looneym and I'm glad you were able to resolve your problem.

**Comment by looneym** [comment]
While we've figured out a way to work around this, the disparity in behaviour between `File.write` and `cp` is confusing and very unexpected. Is this an expected behaviour of refinery? If so should it be documented? We lost a lot of time to this.
