### ISSUE TITLE
Refinery nodes should remove themselves from peer management on shutdown

### ISSUE THREAD

**Issue by MikeGoldsmith** [honeycombio/refinery#393]
**Is your feature request related to a problem? Please describe.**
When using a peer management coordinator (eg Redis) to determine which nodes nodes are active and how to distribute traffic across the cluster, when a node goes down the coordinator has to wait 30 seconds for it to be removed from the cache of active nodes.

**Describe the solution you'd like**
A refinery node on shutdown should remove itself from the cache so that the cache is updated quicker.

**Describe alternatives you've considered**

**Additional context**

**Comment by seh** [comment]
Would the maintainers entertain a patch for this enhancement from an external contributor?

**Comment by MikeGoldsmith** [comment]
This is not immedately on our TODO so we would defiently welcome a contribution 👍🏻
