### ISSUE TITLE
Add default environment prefix to allow environments and dataset with same name in rules file

### ISSUE THREAD

**Issue by MikeGoldsmith** [honeycombio/refinery#408]
**Is your feature request related to a problem? Please describe.**
When configuring refinery rules, you cannot specify both an environment and dataset with the same name. This is possible to configure in Honeycomb - eg a legacy production dataset and a production environment.

**Describe the solution you'd like**
Add a legacy dataset prefix config setting that differentiate between environments and datasets.

The default would be empty, so no prefix is used.

eg
config.toml
```
...
LegacyDatasetPrefix = "legacy"
...
```

rules.toml
```

# environment
[production]
...

# dataset
[legacy.production]
...
```

**Describe alternatives you've considered**

**Additional context**

**Comment by seh** [comment]
Rather than "legacy" being the default prefix, consider the word "dataset" as an alternative.

**Comment by MikeGoldsmith** [comment]
@seh I've created the PR to allow a dataset prefix. Feel free to take a look 👍🏻
