### ISSUE TITLE
Don't send SampleRate in dry run mode

### ISSUE THREAD

**Issue by cartermp** [honeycombio/refinery#415]
It seems quite wrong to send the sample rate when refinery is running in dry run mode. For example, it could mess up your `COUNT`s even though the data isn't actually being sampled.

**Comment by seh** [comment]
I could see sending this field conditionally by way of configuration, but only on events that Refinery _would have sent_ when running wetly. For the events that Refinery would not have sent, they don't represent that approximate number of missing events.

With that approach, you can exclude the events that Refinery wouldn't have sent and inspect the sample rates reported on the events that it would have sent.

**Comment by vreynolds** [comment]
Internal support ticket about DryMode sending Sample Rate being confusing: https://app.asana.com/0/526085303034087/1203714518944317/f
