### ISSUE TITLE
patch openSSL CVE

### ISSUE THREAD

**Issue by vreynolds** [honeycombio/refinery#421]
https://mta.openssl.org/pipermail/openssl-announce/2022-March/000219.html

- [x] Dockerfile: docker alpine waiting for update: https://github.com/alpinelinux/docker-alpine/issues/243
  - use alpine version >= 3.12.11, 3.13.9, 3.15.3 or 3.14.5
- [x] build artifacts: ~~`circleci/golang` image is based on `golang` image which is based on `alpine` - waiting on the same update~~
  - use newer circle images `cimg/go:1.18.1`

**Comment by JamieDanielson** [comment]
circle image updated in #430

**Comment by MikeGoldsmith** [comment]
golang:alpine tag now points to 3.15
