### ISSUE TITLE
optimize rule checks - break out of loop once match is found

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/refinery#434]
**Is your feature request related to a problem? Please describe.**

_Posting from internal discussion:_

Looking at this [code](https://github.com/honeycombio/refinery/blob/153a398d13636722ccd03a2e65ed58d128a6cfbb/sample/rules.go#L67-L72) it appears to evaluate matches:

- for each rule
- for each condition in the rule
- for each span in the trace

and at the end it checks that the number of matches == the number of conditions
So conditions are evaluated independently across all spans in the trace, and then ANDed together.
Rules are ORed in that the first rule for which all conditions are matched will be the rule that is evaluated.

This could be optimized - instead of checking against every span, even after a match is made, break out if a match has been found.

**Describe the solution you'd like**

add this below the `span:` label on [line 71](https://github.com/honeycombio/refinery/blob/main/sample/rules.go#L71). 

```go
if matched == len(rule.Condition) {
    break
}
```

**Additional context**

This code adjustment cannot be added as-is, so using this issue as a placeholder to work on it. (Error: `label span declared but not used.`)

**Comment by fchikwekwe** [comment]
This issue was already addressed in #532. Closing this issue.
