### ISSUE TITLE
Forward important metadata from OTel traces

### ISSUE THREAD

**Issue by cartermp** [honeycombio/refinery#436]
Consider this query: https://ui-dogfood.honeycomb.io/prod/environments/prod/datasets/shepherd/result/Gsmp5wRPqzx

We know from talking to the customer that they're indeed using OpenTelemetry, but because traces go through Refinery, things like the SDK language/version/etc. (which are set as resource attributes in trace data) are missing when we query for it. This makes it hard to debug things when someone is using Refinery.

**Comment by MikeGoldsmith** [comment]
So, we do track these fields in the customer instrumentation when converting from OTLP -> hny event, but those events go the HTTP endpoints in Shepherd and we only extract those fields from events converted in Shepherd directly.

The above PR moves the logic to extract known telemetry fields from events received on OTLP and HTTP endpoints.
