### ISSUE TITLE
Collect Libhoney metrics when using prometheus

### ISSUE THREAD

**Issue by drew-eero** [honeycombio/refinery#446]
Hi All, 

Info: 
 - Refinery deployed to k8s using https://github.com/honeycombio/helm-charts
 - Version 1.13.0 of refinery docker image was used. 
 - Using Prometheus operator to scrape metrics 

I'm not seeing any of the libhoney metrics described in the scaling documentation here https://docs.honeycomb.io/manage-data-volume/refinery/scale-and-troubleshoot/#sizing-the-send-buffers in prometheus. Any idea why I'm getting all the other metrics but not libhoney?

**Comment by MikeGoldsmith** [comment]
Hi @drew-eero - thanks for creating the issue.

It doesn't look like the prometheus metrics in refinery subscribe to libhoney's metrics, it only subscribes to the refinery metrics. I think it is an oversight, and agree they would be useful to add if possible.

I've updated the ticket title to reflect tracking adding libhoney metrics to the prometheus managed metrics. I'm unsure when we'll get a chance to schedule this work, but we're always welcoming of community contributions.

Thanks 👍🏻

**Comment by kentquirk** [comment]
For reference, this is related to #351.

**Comment by masonjlegere** [comment]
We would also like to use Prometheus for some of libhoney metrics. I'll try and make a contribution to add them over the next few days
