### ISSUE TITLE
Cast attributes to a type for samplers

### ISSUE THREAD

**Issue by McSick** [honeycombio/refinery#452]
**Is your feature request related to a problem? Please describe.**
Sometimes the telemetry gets sent as a wrong data type. You can fix this on the Honeycomb side via changing the column type. Refinery is not aware of those changes

**Describe the solution you'd like**
A way to add an optional property that would allow casting the operator before making a decision. Likely to be only needed for the rules based samplers.

**Describe alternatives you've considered**
Making the code send the right type. 

**Additional context**

**Comment by kentquirk** [comment]
This is contained by #541.
