### ISSUE TITLE
Use event sample rate in calculation for refinery's sample rate value

### ISSUE THREAD

**Issue by jwilm** [honeycombio/refinery#490]
On traces that already have a positive `sample_rate` attribute like `10`, Refinery will overwrite it with whatever rate Refinery sampled it at rather than the product of the two rates. Eg, if Refinery samples that trace at a rate of 2, the SampleRate should be set to 20 rather than 2.

This results in Honeycomb under-reporting total event volume and makes it more difficult to reason about span volume.

**Versions**

- Go: any
- Refinery: latest

**Steps to reproduce**

1. Send a span with the `sample_rate` attribute already set to a number greater than 1
2. Observe Refinery overwriting it with whatever rate Refinery samples it at

**Additional context**

We have tail sampling implemented in some of our high volume applications as to not burden our already large Refinery cluster with a bunch of extra work.

**Comment by MikeGoldsmith** [comment]
Hey @jwilm - thanks for raising the issue.

Refinery is not designed to take into account sample rate set on spans/events by the sending app / an intermediate process. I don' think this isn't a bug but an enhancement we could consider adding if required.

I've updated title / label to better represent the ask. Let me know if you think otherwise 👍🏻

**Comment by jwilm** [comment]
Sounds good; I didn't have the context to know which way this one went :wink:.

This would be a very welcome enhancement. As we continue to ramp up our observability efforts, we are finding ourselves needing to do more and more sampling in the applications as to avoid large spend on our Refinery cluster. However, this currently has the drawback of not being able to rely on Honeycomb to know the volume of events since they end up being (sometimes severely) underreported.

**Comment by MikeGoldsmith** [comment]
Sure, I understand your use case and think your proposed solution makes sense. We'd likely want to make this an opt-in feature, so not to affect current users who may expect this current calculations to work as they are now.

I'm unsure when we'll get to this but we're always welcoming of community PRs if you feel you'd like to contribute 👍🏻

**Comment by robbkidd** [comment]
An addendum to this and in the spirit of #473, the implementation of this calculation of a final sample rate ought to include some further (optional?) annotations on the sampled spans about original sample rate (`meta.refinery.original_sample_rate`? `meta.refinery.upsampled_from_rate`? 🤔) so as to leave a bread crumb trail to investigate weird sampling results.

**Comment by kentquirk** [comment]
This was fixed by #508.
