### ISSUE TITLE
Update docs with details on how throughput can be affected by cluster size

### ISSUE THREAD

**Issue by MikeGoldsmith** [honeycombio/refinery#501]
**Is your feature request related to a problem? Please describe.**
The TotalThroughputSampler's throughput is affected by the cluster size, and changing the cluster size (increasing or decreasing the number of nodes) can alter it. This is not reflected in the docs.

**Describe the solution you'd like**
Update docs to describe the relationship between throughput and cluster size and how changing the cluster size may affect the throughput value.

**Comment by TylerHelmuth** [comment]
@MikeGoldsmith @kentquirk does cluster size here refer to the number of nodes in a k8s cluster or the number of refinery peers?  I can't find evidence in the `TotalThroughputSampler` that either would affect performance.

**Comment by robbkidd** [comment]
We'll address this documentation as the scaling and auto-scaling implementation changes in the near-term.
