### ISSUE TITLE
Documented Advice for CacheCapacity setting could be more concise/less confusing

### ISSUE THREAD

**Issue by tdarwin** [honeycombio/refinery#526]
< sorry, this is somewhere between a bug and a feature request, so I chose bug >

The documentation on CacheCapacity is hard to digest.  Namely, we have way too many places where it says something different:

1. [Refinery Configuration Docs](https://docs.honeycomb.io/manage-data-volume/refinery/configuration/#collector:~:text=CacheCapacity,increase%20the%20CacheCapacity%20value.)
2. [Refinery Scaling and Troubleshooting Docs](https://docs.honeycomb.io/manage-data-volume/refinery/scale-and-troubleshoot/#sizing-the-cache:~:text=Sizing%20The%20Cache,match%20collect_cache_capacity.)
3. [The Refinery Repo README](https://github.com/honeycombio/refinery#:~:text=Buffer%20size%3A%20The,of%20the%20buffer.)

These sort of tell different important parts of the story, but it's not well combined, and makes it hard to get these two salient points:

- CacheCapacity is a definition of Number of Traces stored in the Cache prior to a sampling decision being made.  It is a Trace frequency related value.  It is not a quantity of RAM allocated to the Cache.  Given the number of references to MaxAlloc around the CacheCapacity (Including a good starting number being MaxAlloc/10,000 in the Scaling docs), we should be really clear on this.
- There is a hard-coding of [5x the CacheCapacity](https://docs.honeycomb.io/manage-data-volume/refinery/configuration/#collector:~:text=In%20addition%2C%20a%20cache%20remembers%20the%20sampling%20decision%20for%20any%20spans%20that%20might%20come%20in%20after%20the%20trace%20has%20been%20marked%20%E2%80%9Ccomplete%E2%80%9D%20(either%20by%20timing%20out%20or%20seeing%20the%20root%20span)%3B%20that%20capacity%20will%20be%205x%20this%20value.) value that is given as a Cache of trace decisions already made. So if your CacheCapacity is set to 5000 (which you can estimate RAM based on average size of your traces), your TraceDecisionCache is going to be 25000, though how much RAM an entry in the decision cache takes is not clear.  (I don't know if this is still true, but it's documented).

I think that would clear up a lot of things, and probably help clients understand how the cache is used a little more clearly.

Finally, it would be nice if we could provide a metric that could tell us trace size, or average trace time (from start to finish of trace), so that we could provide a calculator for more accurately setting the cache capacity.

Thanks,
~Davin

**Comment by cartermp** [comment]
Probably going to close this since we changed a lot of this in 2.x, but we should chat in slack to see if needs are still met here.
