### ISSUE TITLE
Redis peer prefix/namespace are not configurable

### ISSUE THREAD

**Issue by csmehta** [honeycombio/refinery#544]
**Is your feature request related to a problem? Please describe.**
This is sort of already implemented as 
https://github.com/honeycombio/refinery/blob/main/internal/redimem/redimem.go#L39
```
type RedisMembership struct {
	// Prefix is a way of namespacing your group membership
	Prefix string
	Pool *redis.Pool
	RepeatCount int
}
```
but the value of the prefix is hardcoded to  `refinery` 
https://github.com/honeycombio/refinery/blob/main/internal/peer/redis.go#L94
```
peers := &redisPeers{
		store: &redimem.RedisMembership{
			Prefix: "refinery",
			Pool:   pool,
		},
		...
	}
```

**Describe the solution you'd like**
Expose the prefix as a config under PeerManagement

```
[PeerManagement]
Type = "redis"
RedisPrefix = "refinery"
```

**Comment by kentquirk** [comment]
We're going to be looking at the Redis stuff in some detail very soon, and we're likely to include something like this as part of it. But it might take a few weeks.
