### ISSUE TITLE
Add maxkeys and keyspace size as metrics for dynamic samplers

### ISSUE THREAD

**Issue by puckpuck** [honeycombio/refinery#554]
**Is your feature request related to a problem? Please describe.**
An improperly configured set of fields used to create the keyspace used by the dynamic sampler can be difficult to diagnose.

**Describe the solution you'd like**
Have dynamic samplers report the `MaxKeys` configuration property and current `keyspace size`. Since multiple dynamic samplers can be used, each one would need a unique name to be identified. For samplers configured directly on a dataset/environment then, `<dataset>` should be used. For samplers configured as part of a Rules-based configuration the name should be `<dataset>-<rule-index>-<rule-name>`

**Comment by kentquirk** [comment]
Additional request for both keyspace cardinality (number of items in the keyspace) as well keyspace size in bytes.
