### ISSUE TITLE
refinery systemd service not persisting reboot on Amazon Linux 2

### ISSUE THREAD

**Issue by forney-tehama** [honeycombio/refinery#564]
**Versions**

- Refinery: 1.19.0
- OS: Amazon Linux 2, aarch64 (arm64): 5.10.149-133.644.amzn2.aarch64
- SystemD: systemd 219: `systemd.aarch64 219-78.amzn2.0.20`

**Steps to reproduce**

1. Install via the RPM
2. `sudo systemctl enable refinery.service --now`
3. Service starts successfully (service is present in systemctl and logs are good in journalctl)
4. reboot
5. Service is no longer present in the service list (ie: sudo systemctl | grep refinery)

**Manual Workaround**
1. Append `WantedBy=multi-user.target` to the refinery.services file (at the bottom, under `[Install]`)
2. `sudo systemctl disable refinery.service`
3. `sudo systemctl enable refinery.service`
    1. Note: You should see two lines about adding symlinks: one for the service itself and one for the target
4. Reboot
5. Run: `sudo systemctl | grep refinery` and confirm the service is now present and healthy

I'm curious about how this hasn't been a larger issue but my wild speculation here is that maybe other versions of systemd make a default assumption about what to do when `Wants` and `WantedBy` isn't present; either that or others simply haven't exercised this path or they solved it themselves. For some further reading on those parameters, I found this helpful when I was troubleshooting this issue: https://unix.stackexchange.com/questions/506347/why-do-most-systemd-examples-contain-wantedby-multi-user-target

**Comment by kentquirk** [comment]
This was addressed by #657
