### ISSUE TITLE
Allow proxying OTLP data with a slash in service name

### ISSUE THREAD

**Issue by vreynolds** [honeycombio/refinery#565]
[Internal thread](https://houndsh.slack.com/archives/CDE86Q55X/p1666903491634309)

In some cases, incoming telemetry might have a generated service name (target dataset) that contains a slash. The Events API does not support that, which is what Refinery uses to pass the data along. This is unexpected, because sending plain OTLP in this scenario works, but adding Refinery in the middle breaks.

Updating Events API and libhoneys to allow slashes is one solution we discussed, but that's a big change fraught with peril. Is there anything we can do Refinery-side to mitigate this? (e.g. using OTLP for outbound data)

**Comment by kentquirk** [comment]
OTLP for outbound is one way to solve this, and I think it's something we will do in the foreseeable future, but it's not on the short list. 

A short-term possibility would be slugifying the dataset names on receipt, rather than waiting until after ingestion. This needs testing, but *should* resolve to the same result.

**Comment by vreynolds** [comment]
We're just going to [document](https://github.com/honeycombio/telemetry-team/issues/382) it for now.

**Comment by VinozzZ** [comment]
Another user ran into the same issue when hooking Refinery up to their service.
[Internal Thread](https://houndsh.slack.com/archives/C4M02EG83/p1709929229092229)

**Comment by mterhar** [comment]
@VinozzZ do you think this will get tackled in the next release or two?

**Comment by VinozzZ** [comment]
implemented in this PR https://github.com/honeycombio/refinery/pull/1199
