### ISSUE TITLE
Specifying MetricsAPIKey in config is ignored when REFINERY_HONEYCOMB_API_KEY is set

### ISSUE THREAD

**Issue by fujin** [honeycombio/refinery#582]
**Versions**

- Go:
- Refinery: 1.18

**Steps to reproduce**

1. Set MetricsAPIKey
2. Set REFINERY_HONEYCOMB_API_KEY
3. MetricsAPIKey is not used (HC metrics are sent with REFINERY_HONEYCOMB_API_KEY)

**Additional context**
https://github.com/honeycombio/refinery/blob/main/config/file_config.go#L138

**Comment by kentquirk** [comment]
Hi, @fujin  -- I think I understand what you're getting at, but this is behaving as designed. 

The philosophy of the config system is that system operators, who may not be the ones who manage configuration files, should be able to override configuration values with environment variables.

Admittedly, not everyone likes this design, but that's the way it has worked for years, so we're unlikely to change it now.

I'm going to close this, but if you think I've misunderstood, please feel free to reopen it.
