### ISSUE TITLE
Define constants for rules operators 

### ISSUE THREAD

**Issue by fchikwekwe** [honeycombio/refinery#592]
We have several operators defined in `rules.go` that are reused in `sampler_config.go` for datatype matching. It would be a good idea to define constants for these operators to keep both places on consistent. The list as it stands seems to be. 
```
"exists"
"not-exists"
"!="
"="
 ">"
">="
"<"
"<="
"starts-with"
"contains"
"does-not-contain"
```

Figure out id there any that are missing and define them in `rules.go`.

**Comment by kentquirk** [comment]
Closed by #813
