### ISSUE TITLE
Allow configuration values to be specified for the cluster rather than the instance

### ISSUE THREAD

**Issue by kentquirk** [honeycombio/refinery#608]
There are configuration values in Refinery, such as the GoalThroughputPerSec value used by the TotalThroughputSampler, that are calculated based on the value for a single instance, but the customer experience is to see refinery as an entire cluster. Can we find a way to allow these values to be adjusted by refinery based on the number of peers in the cluster?

This makes it easier to think about as well as meaning that the value wouldn't have to be adjusted when cluster size changes.

**Comment by TylerHelmuth** [comment]
Related to https://github.com/honeycombio/refinery/issues/560
