### ISSUE TITLE
If spans come in with existing Sample Rate > 1, we should annotate them

### ISSUE THREAD

**Issue by kentquirk** [honeycombio/refinery#612]
**Is your feature request related to a problem? Please describe.**

A customer had traces that were matching a rule, but had different sample rates. We eventually figured out that it was due to upstream telemetry setting sample rate (head sampling) but it took a while to get there, because the field "meta.refinery.original_sample_rate" was blank.

This was because we only populate that field if we're going to change the upstream value -- but here Refinery's desired rate was 1, so we weren't changing it. 

We should either:
* Populate that field anytime it's not 0
* Populate some other field that indicates that it was set upstream

**Describe the solution you'd like**
I suggest the first one.

**Describe alternatives you've considered**
Not being confused.

**Additional context**

**Comment by TylerHelmuth** [comment]
I agree, let's populate it any time it is not 0.
