### ISSUE TITLE
Design issue for metrics update

### ISSUE THREAD

**Issue by kentquirk** [honeycombio/refinery#624]
There are a number of issues relating to basic behavior of Metrics in refinery:

* #562 
* #581 
* #446 and #351 

The recent change to metrics in #593 gives us the structure that makes it possible to resolve all of these, since there is now a single metrics instance that can be wrapped.

The plan is:
* Create a wrapper class, multi-metrics, that can duplicate metrics calls to multiple implementations of metrics
* Add the ability to specify multiple metrics implementations in the config (and allow different implementations to specify different refresh intervals)
* Remove the requirement to specify info about the honeycomb metrics if it's not in use
* Add a new `otel` metrics type, which can send metrics via OpenTelemetry
* Make it so metrics sent via the `honeycomb` type will convert histograms into gauges

This enables:
* Sending metrics to multiple destinations -- Honeycomb would very much like to see metrics in Honeycomb, but some users are collecting their metrics via the Prometheus data.
* Easier management of Honeycomb metrics
* Supporting OTel metrics, either to Honeycomb or elsewhere
* Reduction of technical debt

**Comment by oneubauer** [comment]
:wave: Would the addition of labels to metrics be helpful at large, and relate to this design issue?

For example, being able to apply `type` labels to error metrics, particularly those related to 
`upstream_enqueue_errors`  `upstream_response_errors` and `peer_response_errors` would help raise the fidelity of those metrics. The conspicuous absence of this feature from the metrics package makes me wonder if cardinality or other concerns blocked any previous implementation.

(FWIW our particular use case atm involves being able to detect specifically related to 429 rate-limit occurrences)
