### ISSUE TITLE
Make trace fields configurable

### ISSUE THREAD

**Issue by kentquirk** [honeycombio/refinery#626]
**Is your feature request related to a problem? Please describe.**
At least one customer has configured their dataset schema via honeycomb to use alternative fields for trace ID, parent ID, and span ID. But refinery has these fields hardcoded to specific values.

**Describe the solution you'd like**
Make these fields configurable in Refinery -- ideally with an ordered list of possibilities.

**Describe alternatives you've considered**
Existing behavior -- but Refinery is inconsistent with Honeycomb at large.

**Additional context**
Proposed config model:

TraceIdFieldNames: ["trace.trace_id", "trace_id", "traceId"]
ParentIdFieldNames: ["trace.parent_id", "parent_id", "parentId"]
SpanIdFieldNames: ["trace.span_id", "span_id", "spanId"]

All these fields would default to just the "trace.*" form. Helper functions would walk the name list and return the value of the first matching field.

**Comment by TylerHelmuth** [comment]
Is it possible for the data to be transformed before it arrives at refinery so that refinery can do its thing and  alternative fields could be used in Honeycomb? Would it be as simple as duplicating the values across multiple field names?

**Comment by tdarwin** [comment]
It's probably possible to do a duplication of a field value from a non-standard field name to a standard one using the OTEL collector, assuming that they're using the OTEL collector somewhere in the traffic flow... At least, it might allow for converting to an OTEL instrumentation over time by having duplicate values in multiple different trace/parent/span ID related fields.
