### ISSUE TITLE
Adjust logging to have reasonable difference between levels

### ISSUE THREAD

**Issue by kentquirk** [honeycombio/refinery#655]
**Is your feature request related to a problem? Please describe.**
Refinery's logging has a couple of related problems:
* It doesn't support a WARN logging level
* Most of its data is emitted with INFO, so setting log level to ERROR means you get no useful information, and setting it to INFO means that you literally log every span. There's no safe middle ground.

I'll note that you CAN set a dynamic sampler on logs to reduce spamming, but its default target is 10 logs per second, which is still a lot.

**Describe the solution you'd like**
* Add a WARN level.
* Examine existing log entries and adjust the message appropriately so that there is a meaningful difference between different log levels. For example, refinery notifications of stress relief turning on and off should probably be WARN.

**Describe alternatives you've considered**
We see customers setting logging to PANIC, which doesn't help anyone, really.

**Comment by TylerHelmuth** [comment]
Should we also add a DEBUG level?  Would be nice for INFO to be less noisy too I think.
