### ISSUE TITLE
Update docker tagging scheme

### ISSUE THREAD

**Issue by RainofTerra** [honeycombio/refinery#790]
**Is your feature request related to a problem? Please describe.**
Our current docker tagging makes it impossible to to prefer a particular major or minor release, or internally to prefer a particular branch. Also, the "latest" tag is potentially confusing in the case where we need to release a minor update to a previous major version (for example)

**Describe the solution you'd like**
Images based off a release tag (`v2.1.5`) will be tagged with:
major (`2`), major.minor (`2.1`), and semver (`2.1.5`) as well as `latest` (for compatibility)

this will allow users to decide which versions they automatically upgrade to (`major.minor` probably being the recommended one)

Internal images based off a branch will be tagged with `branch-branchname` such as `branch-terra.myawesomebranch`

**Describe alternatives you've considered**
None but it is versioning so I'm sure there are any number of possible versions 😉

**Additional context**

**Comment by cartermp** [comment]
Note for team: consider doing this alongside the work in https://github.com/honeycombio/refinery/issues/869
