### ISSUE TITLE
Expose http.Server.IdleTimeout via configuration

### ISSUE THREAD

**Issue by nickstenning** [honeycombio/refinery#825]
**Is your feature request related to a problem? Please describe.**

Some hosting options for Refinery offer limited configurability of the HTTP keepalive timeouts used by load balancers in front of Refinery. The example I'm most familiar with are GCP load balancers, which have fixed and non-configurable keepalive timeouts of ~10 minutes.

In this situation, it's crucial that upstream/backend services have a _longer_ idle timeout than their clients (the load balancers), otherwise there will always be situations where a load balancer attempts to use a connection that the backend has already discarded.

The impact to clients communicating with Refinery through such a load balancer is typically a low but consistent level of connection reset errors.

**Describe the solution you'd like**

Would it be possible to expose configuration of `http.Server.IdleTimeout` for the [main Refinery HTTP listener](https://github.com/honeycombio/refinery/blob/00fe2b31667c1a3f7b68802ecc637d8ad5eb1ed5/route/route.go#L206) via configuration?

**Describe alternatives you've considered**

Technically I'm sure there are other solutions here, including asking operators of Refinery to deploy a different service (nginx/etc.) between the downstream load balancer and Refinery, but there don't seem to me to be compelling reasons _not_ to expose this knob in Refinery's configuration.

**Additional context**

- https://cloud.google.com/load-balancing/docs/https/#timeout-keepalive-backends
- https://cloud.google.com/load-balancing/docs/https/#timeout-keepalive-clients

**Comment by nickstenning** [comment]
Hey @kentquirk would you accept a PR for this?

**Comment by kentquirk** [comment]
@nickstenning sorry, we were at a conference and I forgot to respond -- yes, we'd take a PR if you have time, but if not we'll plan to get to it soon.
