### ISSUE TITLE
Please provide a more descriptive reason for late-arriving spans

### ISSUE THREAD

**Issue by irvingpop** [honeycombio/refinery#835]
**Is your feature request related to a problem? Please describe.**
When customers first encounter the reason `late`, they're a bit confused and have to ask about it.  I was thinking a more descriptive reason would make it more intuitive.

**Describe the solution you'd like**
If it's possible to know/store the rule name without a significant performance penalty, then perhaps something like `rules/trace/rulename - late arriving span` and could also aid debugging.   If not, perhaps changing the text to `late arriving span` would do enough to quell the confusion.

**Describe alternatives you've considered**
Documentation, although it might be difficult to make the keyword `late` searchable enough.

**Additional context**
Marking late-arriving spans is a super cool feature and has been a huge quality-of-life improvement!  Once people know what it means they totally get it, it's more of a new user issue.

**Comment by kentquirk** [comment]
There have been [requests](https://honeycombpollinators.slack.com/archives/C01BZ3J7RMJ/p1692874128432529) to record the reason and make it available in the late spans.

**Comment by VinozzZ** [comment]
related to #898
