### ISSUE TITLE
Scratch image is operator hostile, can we use a slim?

### ISSUE THREAD

**Issue by mterhar** [honeycombio/refinery#840]
I've been helping support Refinery deployments for a while and every time there are questions about how refinery is doing, the instinct to shell into the pod and see if DNS is broken, ports are open, etc is thwarted by `FROM scratch`. 

If the image was a debian slim or even alpine, a basic shell and some commands would exist to aid in troubleshooting. 

Suggestion 1:

Change the `FROM scratch` line to `FROM debian:stable-slim`

Suggestion 2:

Make 2 dockerfiles, one that builds from scratch for maximum efficiency and one that builds from a thicker image for maximum supportability. 

Open to other suggestions.

**Comment by kentquirk** [comment]
We had some internal discussion about this, and the consensus was that for security reasons, we should not be using or building anything but a scratch image for an executable. 

There are other alternatives, including:
- Building a custom image
- Adding an "empty shell" pod to the cluster
