### ISSUE TITLE
Ignore trailing slash on /v1/traces endpoint

### ISSUE THREAD

**Issue by nlochschmidt** [honeycombio/refinery#867]
**Is your feature request related to a problem? Please describe.**

I just spent a couple of hours trying to figure out why refinery is not applying the sampling to the traces I sent and instead is forwarding all traces directly to honeycomb. As it turns out, I've set the endpoint in my application to `<refineryhost>:8080/v1/traces/`. Once I removed the trailing slash, everything started to work as expected.

**Describe the solution you'd like**

Refinery should work like honeycomb itself. When sending traces to `/v1/traces/` it should ignore the trailing slash and process the trace as expected.

**Describe alternatives you've considered**

I guess an alternative could be to reject the request and respond with the same error that appears when accidentally sending to the root endpoint: 

```
invalid OTLP endpoint - should you be sending to /v1/traces?, see API docs https://docs.honeycomb.io/
```

_Side-Note: The question mark directly behind a URL is a little confusing. Maybe consider adding a space between `/v1/traces` and `?`_

**Additional context**

Of course in hindsight it's all very obvious, but I can easily see myself making that error again in the future.

**Comment by kentquirk** [comment]
We mimic the behavior of the collector in this regard.

**Comment by kentquirk** [comment]
The spec [here](https://opentelemetry.io/docs/specs/otlp/#otlphttp-request) seems to indicate that as long as we support `/v1/traces` we can also support other endpoints, so it seems fine to do this.
