### ISSUE TITLE
Add tracing to Refinery itself

### ISSUE THREAD

**Issue by cartermp** [honeycombio/refinery#868]
Rather than continue to add ever more complex metrics types to somewhat approximate what good tracing can get you, maybe we should generate traces from Refinery's internals and let operators look at those traces to get a more detailed view into the decisions Refinery is making and the volume of data associated with those decisions.

We'd need to have a way to sample these traces we generate - meta-sampling 😆

**Comment by VinozzZ** [comment]
- #1218 completed in this issue
