### ISSUE TITLE
Allow for semi-official builds in CI based on branches

### ISSUE THREAD

**Issue by cartermp** [honeycombio/refinery#869]
When working with customers that have a specific environment and/or configuration, it can often be helpful to take a branch of Refinery and experiment with something that works for them. However, if we want them to use that version of Refinery, the binary isn't built the same way that release binaries are! That can make diagnosing issues more challenging and from a security POV, these builds should go through the same processes as our release builds.

**Comment by kentquirk** [comment]
This basically works today.
