### ISSUE TITLE
Can we have configuration to define GRPCMessageSizeMax?

### ISSUE THREAD

**Issue by nicacioliveira** [honeycombio/refinery#905]
**Is your feature request related to a problem? Please describe.**

We receive traces that are consistently over 5 MB in GRPC packets. Are there any limitations to allowing this configuration? We face significant trace loss due to a context where nearly 30% of the 5 billion daily traces have large label values resulting in direct gRPC packets that are nearly 20 MB in size.

**Describe the solution you'd like**

[I would like to have gRPC max size configuration inside refinery configs.](https://github.com/honeycombio/refinery/blob/main/route/route.go#L52)

**Describe alternatives you've considered**

**Additional context**

Example of error and size of gRPC packet that we have. In the example below we have 10mb.
```txt
Permanent error: rpc error: code = ResourceExhausted desc = grpc: received message after decompression larger than max (10389172 vs. 5000000)
```

**Comment by kentquirk** [comment]
Thank you for this detailed request. It seems quite reasonable, and I think we can make this happen pretty soon.
