### ISSUE TITLE
Update readme to talk about sizing modern refinery (stress relief, etc)

### ISSUE THREAD

**Issue by kentquirk** [honeycombio/refinery#929]
Refinery readme doesn't adequately explain stress relief or sizing refinery; needs a bit of focus to get it right.

**Comment by fchikwekwe** [comment]
This is some good goalie work for me this week. Picking it up.

**Comment by JamieDanielson** [comment]
was this closed by #955 or just updated?

**Comment by kentquirk** [comment]
Ah, forgot the note! Thanks.
