### ISSUE TITLE
Strange increases in memory usage

### ISSUE THREAD

**Issue by dcarley** [honeycombio/refinery#94]
We've seen some strange increases in memory usage that seem to correspond with … 🤔  … less traffic. We're running 10 nodes with a CacheCapacity of 150k each. They normally consume 6.5-7G of memory each, so we've set a limit of 8G. On two occasions now they've ramped up to the limit and have been OOM killed. This appears to repeat until the traffic levels return to normal.

We could increase the memory limit, but it's not clear how much would be required and we haven't been able to reproduce it within our control. We've thought about capturing pprof data from #82 but we're not sure that it will be possible in the small timeframe before the OOM. Is there anything else we should be looking at?

Metrics from during an incident:

![image](https://user-images.githubusercontent.com/260438/89275086-b4061980-d639-11ea-805e-daf7cbc0892e.png)

Metrics from over a weekend (#89 was causing some additional restarts):

![image](https://user-images.githubusercontent.com/260438/89275227-e6b01200-d639-11ea-851f-fcc43929148c.png)

**Comment by dcarley** [comment]
As [mentioned in Slack](https://honeycombpollinators.slack.com/archives/CG8M2GY3U/p1597091288087000), we experienced this again over the weekend. The start and end timing are very spooky 👻 

![image](https://user-images.githubusercontent.com/260438/89921128-3328be00-dbf5-11ea-831c-8236e767b6bd.png)

**Comment by MikeGoldsmith** [comment]
Hey @dcarley - sorry for the delay in getting back to you on this. There have been a couple of related changes to refinery since this issue was raised that could have had an impact, particularly around removing old traces once sent #132.

I'm going to close this issue for now. Please re-open if you feel it's still relevant.
