### ISSUE TITLE
Refinery overwrites config settings by applying defaults after config was loaded

### ISSUE THREAD

**Issue by fchikwekwe** [honeycombio/refinery#954]
[As seen in this section of code](https://github.com/honeycombio/refinery/blob/main/config/configLoadHelpers.go#L232), Refinery is loading in defaults after the config has already been loaded in. This can result in user settings being reset to default. We need to apply defaults first and then load in the config to overwrite sections with user settings.

**Comment by robbkidd** [comment]
After our coding session today, I poked around at `creasty/defaults` and found [their test cases](https://github.com/creasty/defaults/blob/5220e08074d54cf55444eb46c6177f0beb84f43c/defaults_test.go#L579-L592) for "don't override an existing value with a default." I think [this change](https://github.com/creasty/defaults/compare/master...robbkidd:defaults:no-override-bools) demonstrates our failure scenario: a `true` default appearing as the final value despite `false` being set by the user.

**Comment by fchikwekwe** [comment]
Opened an issue while still working on this https://github.com/creasty/defaults/issues/49.

**Comment by fchikwekwe** [comment]
Closed by #969. Upstream work https://github.com/creasty/defaults/pull/50 and https://github.com/creasty/defaults/pull/51.

**Comment by fchikwekwe** [comment]
Followup worked to be done for 2.5 release described in #970.
