### ISSUE TITLE
not-exists is a footgun

### ISSUE THREAD

**Issue by kentquirk** [honeycombio/refinery#965]
We had an incident at Honeycomb where a `not-exists` rule was used with `Scope: trace`, which meant that all traces lacking a particular field in ANY ONE SPAN were set to a sample rate of 1. An otherwise innocent change happened to occur at a time when that field was not added to the span, and it caused every trace to be kept, resulting in DDOSing us. 

It's hard to think of a use case for `not-exists` and `Scope: trace` to be used together. 

[This internal slack thread](https://houndsh.slack.com/archives/C067QGXHWKC/p1704403927884669) discusses it. We should consider what to do about this. Options include:

- [x] #979 
- [x] #993
- ~nerf the feature entirely~

**Comment by robbkidd** [comment]
Resolved with documentation in #979. Maybe we'll do more with warning when the negative operators are used for #993.
