### ISSUE TITLE
Create a metric for traces/spans dropped by drop rules specifically

### ISSUE THREAD

**Issue by tdarwin** [honeycombio/refinery#974]
**Describe the solution you'd like**
We get some decent metrics now on the different samplers and the applied sample rates and drops vs. keeps, but I can't find anything for spans/traces dropped by non-sampler drop rules.  I think folks would like to know how many traces their drop rules are catching and dropping overall.

It might not let them know *what* is being dropped, but at least will give them a good idea of how much traffic is matching those drop rules and being eliminated

**Comment by MikeGoldsmith** [comment]
Thanks for raising @tdarwin - after discussing with the team, we agree this would be useful and are going to provisionally add to the 2.5 release milestone but with 2.5 already quite large may slide to 2.6.
